name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose -- --nocapture
    - name: Run the executable after build
      run: cargo run --release
    - name: Benchmark socketutils vs netstat
      run: |
        echo "Running Socket socketutils benchmark"
        time target/release/socketutils > /dev/null
        echo "Running netstat benchmark"
        time netstat -anltp > /dev/null
